name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump-action.yml
        id: dump
        with:
          enable-context: "true" # 入力パラメータの指定
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }} # アクションの出力値を参照
