name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        default: "Hello"
        type: string
        required: true
        description: "A cheerful word"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
  call-workflow:
    needs: run
    uses: ./.github/workflows/slack-notification.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
    with:
      exitCode: "success"
