name: Slack Notification Workflow
on:
  workflow_call:
    inputs:
      exitCode:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
        description: "Slack Bot Token for notifications"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack - Success
        if: ${{ inputs.exitCode == 'success' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: |
            {
              "text": "✅ GitHub Actions Workflow Succeeded!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "✅ Workflow Succeeded!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}\n*Workflow:* ${{ github.workflow }}"
                  }
                }
              ]
            }

      - name: Notify Slack - Failure
        if: ${{ inputs.exitCode != 'success' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: |
            {
              "text": "❌ GitHub Actions Workflow Failed!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Workflow Failed!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.repository }}\n*Workflow:* ${{ github.workflow }}"
                  }
                }
              ]
            }
