name: Slack Notification Workflow
on:
  workflow_call:
    inputs:
      exitCode:
        required: true
        type: string
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack - Success
        if: ${{ inputs.exitCode == 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "✅ Workflow Succeeded!"
          SLACK_TITLE: "Workflow Result"
          SLACK_COLOR: good

      - name: Notify Slack - Failure
        if: ${{ inputs.exitCode != 'success' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: "❌ Workflow Failed!"
          SLACK_TITLE: "Workflow Result"
          SLACK_COLOR: danger
